import '@/styles/global.css';

// Components
import Header from '@/containers/layout/Header';
import Nav from '@/containers/layout/Nav';
import Footer from '@/containers/layout/Footer';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
